# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('SurName', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=80)),
                ('Phone', models.IntegerField(max_length=11)),
            ],
        ),
    ]
