# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20180114_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='SurName',
        ),
    ]
